# Name your project! Project names should contain only lowercase characters
# and underscores.
name: 'my_dbt_project'
version: '1.0.0'
config-version: 2

# File path configurations
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

# -------------------------
# Global Variables
# -------------------------


# This tells dbt which profile to use.
profile: 'my_dbt_project'

# -------------------------
# Model Configurations
# -------------------------


models:
  my_dbt_project:
  
    intermediate:
      schema: "intermediate"
      +materialized: table
     
    final:
      schema: "final"
      +materialized: table
      

